# POST http://localhost:2000/login
# Content-Type: application/json

# {
#     "account": "kdev2k@gmail.com",
#     "password": "khanh17/"
# }

# POST http://localhost:2000/register
# Content-Type: application/json

# {
#     "username":"kdev2k",
#     "password":"khanh17/",
#     "rePassword": "khanh17/",
#     "email": "kdev2k@gmail.com"
# }

# PATCH http://localhost:2000/active-user
# Content-Type: application/json

# {
#     "activationCode": "68809",
#     "email": "kdev2k@gmail.com"
# }

# PATCH http://localhost:2000/resend-code
# Content-Type: application/json

# {
#     "email": "kdev11@gmail.com"
# }

# POST http://localhost:2000/verify-email 
# Content-Type: application/json

# {
#     "verifyCode": "77177",
#     "email": "kdev11@gmail.com"
# }

# PATCH http://localhost:2000/forgot-password
# Content-Type: application/json

# {
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Ijoia2RldjExIiwiaWF0IjoxNjU5MjU3MjAyLCJleHAiOjE2NTkyNTc4MDJ9.4T0q0vXxISxBtzk0mqf0XW584spxTRP70bFRmNORJo4",
#     "password": "171122k/",
#     "rePassword": "171122k/"
# }

# PATCH http://localhost:2000/change-password 
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Ijoia2RldjExQGdtYWlsLmNvbSIsImlhdCI6MTY1OTI1NzI4NywiZXhwIjoxNjU5MzQzNjg3fQ.ONa_PvmI0Ch6tUi0LgilxHEjVTc1VfDu3OjVQKfojog
# Content-Type: application/json

# {
#     "password": "khanh17/",
#     "rePassword": "khanh17/"
# }

