POST http://localhost:2000/login
Content-Type: application/json

{
    "account": "kdev11@gmail.com",
    "password": "17112k/"
}

# POST http://localhost:2000/register
# Content-Type: application/json

# {
#     "username":"kdev11",
#     "password":"khanh17/",
#     "rePassword": "khanh17/",
#     "email": "kdev11@gmail.com"
# }

# PATCH http://localhost:2000/active-user
# Content-Type: application/json

# {
#     "activationCode": "93715",
#     "email": "kdev11@gmail.com"
# }

# PATCH http://localhost:2000/resend-code
# Content-Type: application/json

# {
#     "email": "kdev11@gmail.com"
# }

# POST http://localhost:2000/verify-email 
# Content-Type: application/json

# {
#     "verifyCode": "60623",
#     "email": "kdev11@gmail.com"
# }

# PATCH http://localhost:2000/forgot-password
# Content-Type: application/json

# {
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtkZXYxMSIsImlhdCI6MTY1OTI0MDM4NiwiZXhwIjoxNjU5MjQwNjg2fQ.7nPs8lZUdT9-hGdgAjDhGvuB3gzQU4_HYDighQMcvMw",
#     "password": "17112k/",
#     "rePassword": "17112k/"
# }

